DROP TABLE IF EXISTS STOCK;

CREATE TABLE STOCK(
    C_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    C_NAME CHAR(20),
    C_DESC TEXT,
    C_QUANTITY INTEGER,
    C_CATEG CHAR(20),
    C_CONDITION CHAR(10),
    C_FINISH CHAR(10),
    C_COMP CHAR(20),
    C_YEAR INTEGER (4),
    PRICE DECIMAL(2,2)
);

INSERT INTO STOCK(C_NAME, C_DESC, C_QUANTITY, C_CATEG, C_CONDITION, C_FINISH, C_COMP, C_YEAR, PRICE) 
VALUES ('test1', 'test1', 1, 'test1', 'test1' , 'test1' , 'test1', 2022, 11.11);
